# Generated by Django 5.2.4 on 2025-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_long_des',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
