# Generated by Django 5.2.4 on 2025-08-17 05:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_genre_service_service_long_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
